development:
  sessions:
    default:
      database: test_task_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: test_task_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: test_task_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
